name: CodeQL Analysis

on: [push]

jobs:
  codeql-analysis:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CodeQL
        uses: github/codeql-action/setup-codeql@v1  # Corrected version

      - name: Perform CodeQL Analysis
        run: |
          # Automatically detects language and performs analysis
          codeql analyze --format=sarif-latest --output=codeql-results.sarif
          
      - name: Upload CodeQL Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: codeql-results.sarif
